version: "3"

services:
  # Sinatraのサンプルアプリケーション
  app:
    build: .

    ports:
      - "10080:4567"

    volumes:
      - .:/app
      - app-bundle:/usr/local/bundle

volumes:
  # Bundlerでインストールされるgemを格納するボリューム
  app-bundle:
