version: "3"

services:
  # Sinatraのサンプルアプリケーション
  app:
    entrypoint: /docker-entrypoint.sh
    build: .

    command: ruby app.rb -o 0.0.0.0

    volumes:
      - .:/app
      - app-bundle:/usr/local/bundle

volumes:
  # Bundlerでインストールされるgemを格納するボリューム
  app-bundle:
